import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { isLocale } from "@/lib/i18n";
import { ReactNode } from "react";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import AppLayoutRouter from '@/components/layout/AppLayoutRouter';
import ExtensionAttrSuppressor from '@/components/ExtensionAttrSuppressor';
import { notFound } from "next/navigation";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "IPHINT",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: Props) {
  const { locale } = await params;

  if (!isLocale(locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className} antialiased bg-white`} suppressHydrationWarning>
        <ExtensionAttrSuppressor />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <StoreProvider>
            <AppLayoutRouter>{children}</AppLayoutRouter>
          </StoreProvider>
        </NextIntlClientProvider>
        
      </body>
    </html>
  );
}