import type { Metadata } from "next";
import { Geist, Geist_Mono, Comfortaa } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { locales, isLocale } from "@/lib/i18n";
import { notFound } from "next/navigation";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ReactNode } from "react";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-comfortaa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Required for static export/caching in the App Router
export function generateStaticParams() {
  return locales.map((locale) => ({
    locale,
  }));
}

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: Props) {
  // In Next.js 16, params must be awaited
  const { locale } = await params;

  // Validate the locale against your central config
  if (!isLocale(locale)) {
    notFound();
  }

  // Fetching messages server-side
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${comfortaa.className} antialiased bg-white`}>
        {/* Pass both 'locale' and 'messages' to the provider */}
        <NextIntlClientProvider locale={locale} messages={messages}>
          <StoreProvider>
            <Navbar />
              {children}
            <Footer />
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}