import type { Metadata } from "next";
import { Geist, Geist_Mono, Comfortaa } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Locale, locales, isLocale } from "@/lib/i18n";
import { notFound } from "next/navigation";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ReactNode } from "react";

// 1. Import the Next-Intl Provider and Server function
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-comfortaa",
});

export const metadata: Metadata = {
  title: "Create Next App", // You can update this later!
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({
    locale,
  }));
}

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: Props) {
  const { locale } = await params;

  if (!isLocale(locale)) {
    notFound();
  }

  // 2. Fetch the dictionary messages for the current locale
  const messages = await getMessages();

  return (
    <html lang={locale}>
      {/* Added bg-white to ensure the light theme starts at the root */}
      <body className={`${comfortaa.className} antialiased bg-white`}>
        
        {/* 3. Wrap everything in the Intl Provider so client components can translate */}
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <Navbar />
            {children}
            <Footer />
          </StoreProvider>
        </NextIntlClientProvider>

      </body>
    </html>
  );
}